//GET NOTE REQUIST

export const GET_NOTE_REQUEST = "GET_NOTES_REQUEST"
export const GET_NOTE_SUCCESS = "GET_NOTES_SUCCESS"
export const GET_NOTE_FAILURE = "GET_NOTES_FAILURE"

export const EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS";
