//
export const GET_MOVIE_DETAILS_LOADING = "GET_MOVIE_DETAILS_LOADING";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_ERROR = "GET_MOVIE_DETAILS_ERROR";
//
export const ADD_MOVIE_DETAILS_LOADING = "ADD_MOVIE_DETAILS_LOADING";
export const ADD_MOVIE_DETAILS_SUCCESS = "ADD_MOVIE_DETAILS_SUCCESS";
export const ADD_MOVIE_DETAILS_ERROR = "ADD_MOVIE_DETAILS_ERROR";
//
export const UPDATE_MOVIE_DETAILS_LOADING = "UPDATE_MOVIE_DETAILS_LOADING";
export const UPDATE_MOVIE_DETAILS_SUCCESS = "UPDATE_MOVIE_DETAILS_SUCCESS";
export const UPDATE_MOVIE_DETAILS_ERROR = "UPDATE_MOVIE_DETAILS_ERROR";
//
export const DELETE_MOVIE_DETAILS_LOADING = "DELETE_MOVIE_DETAILS_LOADING";
export const DELETE_MOVIE_DETAILS_SUCCESS = "DELETE_MOVIE_DETAILS_SUCCESS";
export const DELETE_MOVIE_DETAILS_ERROR = "DELETE_MOVIE_DETAILS_ERROR";
